name: API - Integración Contínua

on:
  push:
    branches:
      - main
    paths:
      - 'src/api/**'

  pull_request:
    branches:
      - main
    paths:
      - 'src/api/**'

jobs:
  
  build:

    name: Compilación y pruebas unitarias

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/api
    
    steps:

      - name: Inicializar el repositorio
        uses: actions/checkout@v3
      
      - name: Obtener Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Compilar la API
        run: go build -v
      
      # Añadir el paso de pruebas unitarias cuando se implementen