name: Documentación - Integración Continua

on:
  push:
    branches:
      - "main"
    paths:
      - "doc/**"
  pull_request:
    paths:
      - "doc/**"

jobs:
  
  build:
    
    name: Compilación y comprobación de la documentación

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./doc

    steps:

    - name: Inicializar el repositorio
      uses: actions/checkout@v3
    
    - name: Escanear documento LaTeX con TeXtidote
      uses: ChiefGokhlayeh/textidote-action@v5
      id: lint
      with:
        root_file: proyecto.tex
        working_directory: doc

    - name: Publicar el informe de TeXtidote
      uses: actions/upload-artifact@v2
      with:
        name: textidote_report
        path: doc/report.html

    - name: Compilar documentación
      uses: xu-cheng/latex-action@v2
      with:
        root_file: proyecto.tex
        working_directory: doc
    
    - name: Publicar el documento PDF creado mediante LaTeX
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/upload-artifact@v2
      with:
        name: memoria-tfg
        path: doc/proyecto.pdf