name: Telegram Bot Collector VidyaSale - Integración Continua

on:
  push:
    branches:
      - main
    paths:
      - "src/bot/telegram/collector/**"
  pull_request:
    paths:
      - "src/bot/telegram/collector/**"

env:

  GO_VERSION: "1.20"

jobs:

  build:

    name: Compilación del bot

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/bot/telegram/collector/

    steps:

    - name: Inicializar el repositorio
      uses: actions/checkout@v4

    - name: Obtener Go para la compilación
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Compilar el bot
      run: go build
    
    - name: Ejecutar las pruebas
      run: go test -v ./...